### ISSUE TITLE
How can i run in local server?

### ISSUE THREAD

**Issue by HKTIBIA** [ivankayzer/gielda-gier#5]
can u help me ?

**Comment by ivankayzer** [comment]
Hi,

run these commands to setup this project

```php
cp .env.example .env
composer install
npm install
npm run dev
php artisan key:generate
```

Now fill in your database credentials in .env and after that run migrations:

```php
php artisan migrate
```

In case you need test data run seed command:
```php
php artisan db:seed
```


Feel free to reopen this issue if you have further questions

**Comment by HKTIBIA** [comment]
development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Frank\AppData\Roaming\npm-cache\_logs\2020-05-14T14_07_09_527Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by ivankayzer** [comment]
What version of Node.js are you running?

**Comment by HKTIBIA** [comment]
most recently, but i will check again

**Comment by HKTIBIA** [comment]
it's possible run in xampp? Directly

**Comment by HKTIBIA** [comment]
you wanna talk to me on telegram ?

**Comment by ivankayzer** [comment]
Unfortunately it doesn't work with the latest node, maybe I will get my hands on it in the near future but can't promise.

Tested right now with Node.js 10.20.1 and works fine. 

Yeah, I think you can run it using XAMPP you just need to downgrade your Node.js. On Windows I would recommend using [Laragon](https://laragon.org/) switching versions is really easy there.

**Comment by HKTIBIA** [comment]
Laragon runs Node.js 11, so how can do this ?

Laragon Full: Apache 2.4, Nginx, MySQL 5.7, PHP 7.2, Redis, Memcached, Node.js 11, npm, yarn, git,…
Download Laragon - Full (130 MB)

**Comment by ivankayzer** [comment]
https://forum.laragon.org/topic/1005/tutorial-how-to-add-another-node-js-version-to-laragon-node-v12-13

**Comment by HKTIBIA** [comment]
So i will do this for Node.js 10.20.1

**Comment by HKTIBIA** [comment]
almost there, can u help me now ?


PHP Warning:  require(/root/gi/vendor/autoload.php): failed to open stream: No such file or directory in /root/gi/artisan on line 18
PHP Fatal error:  require(): Failed opening required '/root/gi/vendor/autoload.php' (include_path='.:/usr/share/php') in /root/gi/artisan on line 18

**Comment by HKTIBIA** [comment]
Hey i setup, but i put on online ?  I MIGRATE TO A LINUX SERVER .

how get this? move to var/www/ folder ?

**Comment by HKTIBIA** [comment]
i run !! but now 

![image](https://user-images.githubusercontent.com/26504139/82003989-2ae1d680-9638-11ea-8348-8a34ed7372c4.png)

.css files doesn't work in server.php

and in /public/ > works fine only index.php? 

how can i fix this?

**Comment by HKTIBIA** [comment]
work fine in public 

![image](https://user-images.githubusercontent.com/26504139/82004741-0555cc80-963a-11ea-9afc-758bc9eabe2f.png)

but when i click in any link 


![image](https://user-images.githubusercontent.com/26504139/82004760-11418e80-963a-11ea-9549-e8ee07c5e357.png)

how can i fix this too?

**Comment by ivankayzer** [comment]
You need to serve /public as a root of your website.

Here is the guide on configuring apache on Linux: https://www.howtoforge.com/tutorial/install-laravel-on-ubuntu-for-apache/

**Comment by HKTIBIA** [comment]
![image](https://user-images.githubusercontent.com/26504139/82066576-fd337680-96a5-11ea-93a1-0fec4d32f091.png)

From this guide on configuring apache on Linux: https://www.howtoforge.com/tutorial/install-laravel-on-ubuntu-for-apache/

i do all step starting Configuring Apache

but doesn't work

**Comment by HKTIBIA** [comment]
only index.php works

**Comment by HKTIBIA** [comment]
WORKS FINE NOW !!!!!!!!!!!!!!!!!!!!!! UHULLLLLLLLLLLLLLLLLL

I restored .htacess
but now
