### ISSUE TITLE
TRY EDIT A PERFIL

### ISSUE THREAD

**Issue by HKTIBIA** [ivankayzer/gielda-gier#6]
SHOW THIS ERROR :

ErrorException (E_ERROR)
Trying to get property 'name' of non-object (View: /var/www/html/gi/resources/views/partials/header.blade.php) (View: /var/www/html/gi/resources/views/partials/header.blade.php) (View: /var/www/html/gi/resources/views/partials/header.blade.php)
Previous exceptions
Trying to get property 'name' of non-object (View: /var/www/html/gi/resources/views/partials/header.blade.php) (View: /var/www/html/gi/resources/views/partials/header.blade.php) (0)
Trying to get property 'name' of non-object (View: /var/www/html/gi/resources/views/partials/header.blade.php) (0)
Trying to get property 'name' of non-object (0)

**Comment by ivankayzer** [comment]
Which line of code throws that error?

**Comment by HKTIBIA** [comment]
i delete  <span><?php echo e(auth()->user()->city->name); ?></span> and works fine, but i lost some thing

then when i try enter in /moj-profil

same error  and i delete in cecb0....php > city, and works fine in line >
<span><?php echo e($user->name); ?></span>

this occur when i try edit profile and change city, looks like a brokeup connection.

**Comment by ivankayzer** [comment]
Did you select a city during registration? If not try adding it to your user directly in database and see if it works.
